#+title: Typst
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* General Info

Typst is a markup like typsetting system written in Rust.

* Webpage

** General

https://typst.app/

** Github

https://github.com/typst/typst

* Text formatting
** Headings

(no backticks needed, here used due to the org mode)

`= H1`

`== H2`

`==== H3`

etc.

** Lists
*** Numbered

(no backticks needed, here used due to the org mode)

`+ Intem 1`

`+ Intem 2`

`+ Intem 3`,

etc.

*** Bulleted

(no backticks needed, here used due to the org mode)

`- Item 1`,

`- Item 2`,

`- Item 3`,

etc.

** Emphasis
*** Italics

(no backticks needed, here used due to the org mode)

`_italicized text_`

*** Bold

(no backticks needed, here used due to the org mode)

`*bold text*`

*** Underline

(no backticks needed, here used due to the org mode)

`#underline[underlined_text]`

** Raw

You may use raw text with verbatim mono-space font and optional syntax
highlighting (useful for code snippets).

*** Examples

For inline code `snippet`.

For code block:

(backticks instead of ', here used due to the org mode)

#+BEGIN_QUOTE

'''rust
fn main() {
    println!("Hello World!");
}
'''
#+END_QUOTE

Constructing the element prgrammatically:

#+BEGIN_QUOTE

#raw("fn " + "main() {}", lang: "rust")

#+END_QUOTE

which will give:

#+BEGIN_QUOTE

fn main() {}

#+END_QUOTE
