#+title: Ch01
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Getting Started
** Help

type ':?' at GHCI to list help options/hints.

** Comments

#+begin_src

-- this is a comment

#+end_src

** Arithmetic

Rather standard, but a quirk in writing negative numbers:

#+begin_src

-- works OK
-3

-- but this one produces an error,
-- since unary, - operator, cannot be mixed with infix operators
2 + -3

-- use parenthesis instead
2 + (-3)

-- or negate function
2 + negate 3

#+end_src

** Comparisons

Rather standard, but quirks:

#+begin_src

-- \= instead of !=
2 \= 3

-- not instead of !
not True

#+end_src

** Info

Info on operators (associativity, precedence, etc.)

#+begin_src

-- :i short for :info
:i +

-- or

:i (*)

#+end_src

** Constants

Mathematical constants:

#+begin_src

-- famous pi
pi

-- but no famous e
e -- produces error

-- for e use
exp 1

#+end_src

** Exponentiation

#+begin_src

-- ^ to raise to integer power
2^10

-- ** to raise to float power
9 ** (0.5) -- equivalent to: sqrt 9

#+end_src

** Ranges

#+begin_src

[1..5]
-- [1,2,3,4,5]

[-2..2]
-- [-2,-1,0,1,2]

[10..1]
-- []

[10,9..1]
-- [10,9,8,7,6,5,4,3,2,1]

[1,4..15]
-- [1,4,7,10,13]

['a'..'d']
-- "abcd"

['f','e'..'a']
-- "fedcba"

[1,1.25..2]
--- [1.0,1.25,1.5,1.75,2.0]

[0,0.1..0.4] -- be careful with floats/doubles
--- [0.0,0.1,0.2,0.30000000000000004,0.4]

[0,1/3..1]
-- [0.0,0.3333333333333333,0.6666666666666666,1.0]

[1..1.8] -- be careful with floats/doubles
-- [1.0,2.0]

--- [1..] -- infinite range (not to execute on its own)
#+end_src

** Lists

Lists must be uniform (the same type of all elements)

Operators:

#+begin_src

[1,2] ++ [3, 4] -- concatenation
-- [1,2,3,4]

3 : [2, 1] -- prepending
-- [3,2,1]

1 : [] -- prepending
-- [1]

#+end_src

** Strings

Strings are just lists of characters.

#+begin_src

['h', 'e', 'l', 'l', 'o']
-- "hello"

"" == []
-- True

#+end_src

`putStrLn` is an equivalent (kind of) of `print` from other programming languages.

#+begin_src

putStrLn "hello"

#+end_src

** Types

#+begin_src

:set +t -- in GHCI it makes type of an expression to be printed after the expression
-- 'it' in the output below is a special variable that stores the result of last command/expression

'c'
-- 'c'
-- it :: Char

#+end_src

#+begin_src

:unset +t -- revokes ':set +t'

'a'
-- 'a'

:type 'a' -- gets the type even without ':set +t' option
-- 'a' :: Char

:t it -- gets the type even without ':set +t' option (shortcut for ':type it')
-- 'a' :: Char

#+end_src

** Simple Program

A program that counts number of lines in text (modifications by me).

#+begin_src

-- file textLinesCounter.hs

getLinesCount :: String -> String
getLinesCount txt = show(length(lines txt)) ++ "\n"

main :: IO ()
main = interact $ getLinesCount -- interact :: (String -> String) -> IO ()

#+end_src

#+begin_src

$ runghc textLinesCounter.hs < test.txt

#+end_src

** Exercises
*** Exercise 1

Use the 'words' function to count the number of words in a string.
You may modify the program from 'Simple Program' above.

#+begin_src

-- file textWordsCounter.hs

getWordsCount :: String -> String
getWordsCount txt = show(length(words txt)) ++ "\n"

main :: IO ()
main = interact $ getWordsCount

#+end_src

#+begin_src

$ runghc textWordsCounter.hs < test.txt

#+end_src

*** Exercise 2

Modify the program from 'Exercise 1' above to get the characters count.

#+begin_src

-- file textCharsCounter.hs

getCharsCount :: String -> String
getCharsCount txt = show(length txt) ++ "\n"

main :: IO ()
main = interact $ getCharsCount

#+end_src

#+begin_src

$ runghc textCharsCounter.hs < test.txt

#+end_src
