#+title: Ch02
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Types and Functions

Haskell's type system is: strong, static and inferred (when needed).

In Haskell there is no implicit type coercion (ergo you must be explicit).

In Haskell the data gets copied instead of being modified in place (so small
performance penalty).

Haskell's type-classes add plasticity to the language's type system.

Thanks to the language type system, we don't need (that many) tests (like in
dynamic programming languages).

* Some Common Basic Types

'Char' - a Unicode character

'Bool'

'Int' - the Haskell standard only guarantees that it is wider than 28 bits
(depending on a machine it may be 32-bit or 64-bit wide)

'Integer' - unbounded 'Int'

'Float' and 'Double' - 32-bit and 64-bit float representation

* Function Application

In Haskell functions are used in prefix notation.

#+begin_src

odd 1
-- True

odd 2
-- False

even 2
-- True

#+end_src

Function application got higher precedence than using operators.

#+begin_src

add3 :: Num a => a -> a
add3 x = x + 3

add3 2 * 6
-- 30

(add3 2) * 6
-- 30

add3 (2 * 6)
-- 15

#+end_src

* Useful Composite Data Types: Lists and Tuples

A composite data type is constructed of other types.

Lists are polymorphic (a list can have any type), but all its elements must be
of the same type.

A type must start with an uppercase letter (like: 'Bool'), a type variable
starts with a lowercase letter (like '[a]').

Lists are "bread and butter" of Haskell collections.

A tuple is a fixed-size collection of values, where each value can have a
different type.

We write a tuple by enclosing its elements in parenthelis and separating it with
commas.

#+begin_src

:t ("Do you like Haskell?", True)
-- ("Do you like Haskell?", True) :: (String, Bool)

()
-- a tuple of zero elements, also known as "unit"
-- somewhat similar to C's void

#+end_src

Haskell doesn't have a notion of a one-element tuple.

Tuples containing different numbers or types of elements have distinct types.

#+begin_src

:t (False, 'a')
-- (False, 'a') :: (Bool, Char)

-- which is different from

:t ('a', False)
-- ('a', False) :: (Char, Bool)

#+end_src

* Functions Over Lists and Tuples

'take' - takes first 'n' elts of a list (if possible)
'drop' - drops first 'n' elts of a list (if possible)

'fst' - get first elt of a two-elt tuple
'snd - get second elt of a two-elt tuple

* Function Types and Purity

#+begin_src

:t lines
-- lines :: String -> [String]
-- splits a string on line boundaries

lines "London, UK\nParis, France"
-- ["London, UK","Paris, France"]

#+end_src

In Haskell functions with side effects got 'IO' in their type signature, e.g.

#+begin_src

:t readFile
-- readFile :: FilePath -> IO String

#+end_src
