#+title: Ch02
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Types and Functions

Haskell's type system is: strong, static and inferred (when needed).

In Haskell there is no implicit type coercion (ergo you must be explicit).

In Haskell the data gets copied instead of being modified in place (so small
performance penalty).

Haskell's type-classes add plasticity to the language's type system.

Thanks to the language type system, we don't need (that many) tests (like in
dynamic programming languages).

* Some Common Basic Types

'Char' - a Unicode character

'Bool'

'Int' - the Haskell standard only guarantees that it is wider than 28 bits
(depending on a machine it may be 32-bit or 64-bit wide)

'Integer' - unbounded 'Int'

'Float' and 'Double' - 32-bit and 64-bit float representation

* Function Application

In Haskell functions are used in prefix notation.

#+begin_src

odd 1
-- True

odd 2
-- False

even 2
-- True

#+end_src

Function application got higher precedence than using operators.

#+begin_src

add3 :: Num a => a -> a
add3 x = x + 3

add3 2 * 6
-- 30

(add3 2) * 6
-- 30

add3 (2 * 6)
-- 15

#+end_src

* Useful Composite Data Types: Lists and Tuples

A composite data type is constructed of other types.

Lists are polymorphic (a list can have any type), but all its elements must be
of the same type.

A type must start with an uppercase letter (like: 'Bool'), a type variable
starts with a lowercase letter (like '[a]').

Lists are "bread and butter" of Haskell collections.

A tuple is a fixed-size collection of values, where each value can have a
different type.

We write a tuple by enclosing its elements in parenthelis and separating it with
commas.

#+begin_src

:t ("Do you like Haskell?", True)
-- ("Do you like Haskell?", True) :: (String, Bool)

()
-- a tuple of zero elements, also known as "unit"
-- somewhat similar to C's void

#+end_src

Haskell doesn't have a notion of a one-element tuple.

Tuples containing different numbers or types of elements have distinct types.

#+begin_src

:t (False, 'a')
-- (False, 'a') :: (Bool, Char)

-- which is different from

:t ('a', False)
-- ('a', False) :: (Char, Bool)

#+end_src

* Functions Over Lists and Tuples

'take' - takes first 'n' elts of a list (if possible)

#+begin_src

-- definition, simplistic example
myTake :: Int -> [a] -> [a]
myTake _ []     = []
myTake 0 _      = []
myTake n (x:xs) = x : myTake (n-1) xs

#+end_src

'drop' - drops first 'n' elts of a list (if possible)

#+begin_src

-- definition, simplistic example
myDrop :: Int -> [a] -> [a]
myDrop _ []     = []
myDrop 0 xs     = xs
myDrop n (_:xs) = myDrop (n-1) xs

#+end_src

'fst' - get first elt of a two-elt tuple

#+begin_src

-- definition, simplistic example
myFst :: (a, b) -> a
myFst (x, _) = x

#+end_src

'snd - get second elt of a two-elt tuple

#+begin_src

-- definition, simplistic example
mySnd :: (a, b) -> b
mySnd (_, y) = y

#+end_src

* Function Types and Purity

#+begin_src

:t lines
-- lines :: String -> [String]
-- splits a string on line boundaries

lines "London, UK\nParis, France"
-- ["London, UK","Paris, France"]

#+end_src

In Haskell functions with side effects got 'IO' in their type signature, e.g.

#+begin_src

:t readFile
-- readFile :: FilePath -> IO String

#+end_src

* Source Files

The file names customarily end with '.hs' suffix and are loaded into ghci with
':load' or ':l' (shortcut) commands.

#+begin_src

:l file.hs

fnFromFileHs arg1 arg2
-- result of fnFromFileHs

#+end_src

The file to be loaded should be in the current working directory, the command
':cd /other_dir' changes the current working directory.

* Return

There is no 'return' keyword in the traditional programming language sense of meaning.
The existing 'return' keyword is a different beast entirely.
A function is a single expression whose value is returned, like in

#+begin_src

add3 :: Num a => a -> a
add3 x = x + 3

add3 1
-- 4

#+end_src

where the result of 'x + 3' (here '4') is returned.

* Variables

A variable is a name to an expression. Once a variable is bound to an
expression, it cannot be changed (kind of like constants in another languages).

#+begin_src

x = 10
x = 11 -- will throw an error, cannot assign a value to x twice

#+end_src

* Conditional Evaluation


#+begin_src

-- definition, simplistic example
myDrop :: Int -> [a] -> [a]
myDrop _ []     = []
myDrop n xs = if n <= 0 then xs
              else myDrop (n-1) (tail xs)

#+end_src

Indentation is important, 'if' clause always has 'then' clause end 'else'
clause. Moreover, it must be type stable (just like a function, and that is why
'else' clause is obligatory). 'If' always includes 'Bool' statement (no
truthy/falsy), 'else' may have an 'if' inside (nested 'if'/'else').
