#+title: Ch02
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Types and Functions

Haskell's type system is: strong, static and inferred (when needed).

In Haskell there is no implicit type coercion (ergo you must be explicit).

In Haskell the data gets copied instead of being modified in place (so small
performance penalty).

Haskell's type-classes add plasticity to the language's type system.

Thanks to the language type system, we don't need (that many) tests (like in
dynamic programming languages).

* Some Common Basic Types

'Char' - a Unicode character

'Bool'

'Int' - the Haskell standard only guarantees that it is wider than 28 bits
(depending on a machine it may be 32-bit or 64-bit wide)

'Integer' - unbounded 'Int'

'Float' and 'Double' - 32-bit and 64-bit float representation

* Function application

In Haskell functions are used in prefix notation.

#+begin_src

odd 1
-- True

odd 2
-- False

even 2
-- True

#+end_src

Function application got higher precedence than using operators.

#+begin_src

add3 :: Num a => a -> a
add3 x = x + 3

add3 2 * 6
-- 30

(add3 2) * 6
-- 30

add3 (2 * 6)
-- 15

#+end_src
