#+title: Ch03
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Defining Types, Streamlining Functions
* Defining New Data Type

#+begin_src

data BookInfo = Book Int String [String] deriving (Show)
-- Book iD title authors

#+end_src

'BookInfo' - name of new type (a type constructor)
'Book' - name of a value constructor

value constructor and type constructor often have the same name

Once new type was defined we can inspect it in GHCI

#+begin_src

:t BookInfo
-- or
:t Book 1 "title" ["author 1", "author 2"]

#+end_src

* Type Synonyms

#+begin_src

type CustormerID = Int
type Name = String

-- which can now be used in

data Customer = Customer CustomerID Name

#+end_src

* Algebraic Data Types (ADTs)

#+begin_src

data Bool = False | True
-- a type with two value constructors
-- it can be either (| - or) one of the value constructors

#+end_src

* ADTs vs Tuples

ADTs allow to distinguish between otherwise identical pieces of information,
e.g.

#+begin_src

type CustormerID = Int
type Name = String
data Customer = Customer CustomerID Name

customer = Customer 2 "John Smith"

-- vs

customer = (2, "John Smith")

#+end_src

The above properties of ADTs help to reduce the number of mistakes in the code.

* Structures

#+begin_src

// c example
struct book_info {
    int id;
    char *title;
    char **authors;
}

-- hs equivalent
data BookInfo = Book Int String [String]
                deriving (Show)

-- hs equivalent (Record Syntax)
data BookInfo = Book {
     bookId  :: Int,
     title   :: String,
     authors :: [String]
     } deriving (Show)

#+end_src

* Enums

#+begin_src

enum Color = Red | Green | Blue  deriving (Eq, Show)

Red == Green
-- False

Blue == Blue
-- True

#+end_src

* Pattern Matching

#+begin_src

mySum :: Num a => [a] -> a
mySum []     = 0
mySum (x:xs) = x + mySum xs

#+end_src

It works because a list, e.g.

- '[1, 2, 3]' is actually '(1:(2:(3:[])))', so '1' is 'x' and (2:(3:[])) is 'xs'
- '[1, 2]' is actually '(1:(2:[]))', so '1' is 'x' and '(2:[])' is 'xs'
- '[1]' is actually '(1:[])', so '1' is 'x' and '[]' is 'xs',
  etc.

  Patterns are matched in the order from top to bottom.

* Construction and Deconstruction

Construction is when we apply some values to constructor, e.g. 'Just 1.25'.

Deconstruction is when we pattern match against the constructor, e.g in a
function. The initial value/variable is not destroyed (it's just the name).

#+begin_src

x = Just 1.25
y = Nothing

extract :: Maybe a -> a -> a
extract (Just x) _  = x
extract Nothing def = def

extract x 0.0
-- 1.25

x
-- Just 1.25

extract y 0.0
-- 0.0

y
-- Nothing

#+end_src

* Naming in Patterns

'a', 'b' - is common in function signature

'(x:xs)' is common in function body

'_' - wild card pattern is common in function body for the part we don't care
about

* Exclusiveness

The patterns should be exclusive or they may be an error, e.g. like in the non
exclusive pattern below:

#+begin_src

mySum :: Num a => [a] -> a
-- mySum []     = 0
mySum (x:xs) = x + mySum xs

#+end_src

* Record Syntax

Record Syntax looks like:

#+begin_src

data BookInfo = Book {
     bookId  :: Int,
     title   :: String,
     authors :: [String]
     } deriving (Show)

#+end_src

and allows us to define a struct with two styles, e.g.:

#+begin_src

book1 = Book 1 "title1" ["author1", "author2"]

#+end_src

or


#+begin_src

book2 = Book {
        id = 2,
        title = "title2",
        authors = ["author1", "author2"]
}

#+end_src

The 'field = name' syntax allows for the fields to be in any order. The commas
may be at end of lines or at beginning of the lines.

With record syntax we get field accessors/getters for free, e.g.:

#+begin_src

:t bookId
-- bookId :: BookInfo -> Int

bookId book1
-- 1

bookId book2
-- 2

#+end_src

* Parameterized Types

Some types are polymorphic, case in point is a list, which elements can be of
any type. The types themselves can be polymorphic too. For that we use type
variables in a type declaration, e.g.

#+begin_src

data Maybe a = Just a | Nothing

:t Just 1.5
-- Just 1.5 :: Fractional a => Maybe a

#+end_src

* Recursive Types

A type is recursive when it is defined in terms of itself, like a list (below Lisp like version)

#+begin_src

data List a = Cons a (List a) | Nil deriving (Show)

x = Cons 0 Nil
-- or
x = Cons 1 (Cons 0 Nil)
-- or
x = Cons 2 (Cons 1 (Cons 0 Nil))
--- etc.

#+end_src

or a Tree

#+begin_src

data Tree a = Node a (Tree a) (Tree a) | Empty deriving (Show)

x = Node 2 (Node 1 Empty Empty) (Node 3 Empty Empty)

#+end_src

* Reporting Errors

There is a standard function 'error :: String -> a' to throw an (unrecoverable)
error. The result is 'a' so that it can be called anywhere and it always have
the right type, e.g.

#+begin_src

myHead :: [a] -> a
myHead (x:xs) = x
myHead []     = error "no head in an empty list"

#+end_src

* Error Alternative

#+begin_src

safeHead :: [a] -> Maybe a
safeHead (x:xs) = Just x
safeHead []     = Nothing

#+end_src

* Local Variables

You can introduce local variables in a function by using 'let' and 'in' keywords.

#+begin_src

getBMI :: Fractional a => a -> a -> a
getBMI weightKg heightCm = let heightM = heightCm / 100
                               bmi = weightKg / (heightM * heightM)
                           in bmi

getBMI 100 200
-- 25.0

getBMI 55 162
-- 20.957171162932475

#+end_src

You can introduce local variables in a function by using 'where' clause.

#+begin_src

getBMI :: Fractional a => a -> a -> a
getBMI weightKg heightCm = bmi
  where heightM = heightCm / 100
        bmi = weightKg / (heightM * heightM)

getBMI 100 200
-- 25.0

getBMI 55 162
-- 20.957171162932475

#+end_src

* Local Functions

The above could be used to introduce local functions.

#+begin_src

getBMIs :: Fractional a => [(a, a)] -> [a]
getBMIs whs = map getBMI whs
  where getBMI (w, h) = w / (h/100 * h/100)

getBMIs [(100, 200), (55, 162)]
-- [25.0, 20.95717116293248]

#+end_src

The same could be done with type declaration for the local function.

#+begin_src

getBMIs :: Fractional a => [(a, a)] -> [a]
getBMIs whs = map getBMI whs
  where getBMI :: Fractional a => (a, a) -> a
        getBMI (w, h) = w / (h/100 * h/100)

getBMIs [(100, 200), (55, 162)]
-- [25.0, 20.95717116293248]

#+end_src

* Tabs vs Spaces

In Haskell you should use spaces for your indentation. The reason is
portability. In case of a fixed-width font, tabs stops are placed at different
intervals on different machines with different OSes. This could read to
interpretation problems for humans reading the code and even compilation
problems for compilers.

* The Case Expression

#+begin_src

x = Just 1.25
y = Nothing

extract :: Maybe a -> a -> a
extract maybe def =
  case maybe of
    Nothing -> def
    Just x  -> x

extract x 0.0
-- 1.25

x
-- Just 1.25

extract y 0.0
-- 0.0

y
-- Nothing

#+end_src

* Conditional Evaluation with Guards

#+begin_src

getBMI :: (Ord a, Fractional a) => a -> a -> Maybe a
getBMI weightKg heightCm
  | (weightKg > 0) && (heightCm > 0) = Just bmi
  | otherwise = Nothing
  where heightM = heightCm / 100
        bmi = weightKg / (heightM * heightM)

getBMI 100 200
-- Just 25.0

getBMI 000 200
-- Nothing

#+end_src

* Exercises
** Exercise 1

Write a function converting List to list, i.e. 'Cons 1 (Cons 0 Nil)' -> '[1, 0]'

#+begin_src

fromList :: List a -> [a]
fromList Nil         = []
fromList (Cons x xs) = x : fromList xs

-- examples

fromList Nil
-- []

fromList (Cons 0 Nil)
-- [0]

fromList (Cons 0 (Cons 1 Nil))
-- [0, 1]

fromList (Cons 0 (Cons 1 (Cons 2 Nil)))
-- [0, 2]

#+end_src

** Exercise 2

Write a function converting list to List, i.e. '[1, 0]' -> 'Cons 1 (Cons 0 Nil)'

#+begin_src

toList :: [a] -> List a
toList []     = Nil
toList (x:xs) = Cons x (toList xs)

-- examples

toList []
-- Nil

toList [1]
-- Cons 1 Nil

toList [0, 1]
-- Cons 0 (Cons 1 Nil)

toList [1..5]
-- Cons 1 (Cons 2 (Cons 3 (Cons 4 (Cons 5 Nil))))

#+end_src

** Exercise 3

Write a function that counts elements of a list.

#+begin_src

countElts :: [a] -> Int
countElts []     = 0
countElts (x:xs) = 1 + countElts xs

#+end_src

or

#+begin_src

countElts :: [a] -> Int
countElts xs = countElts' xs 0
  where
    countElts' [] acc     = acc
    countElts' (x:xs) acc = countElts' xs (acc + 1)

#+end_src

or

#+begin_src

countElts' :: [a] -> Int -> Int
countElts' [] acc     = acc
countElts' (x:xs) acc = countElts' xs (acc + 1)

countElts :: [a] -> Int
countElts xs = countElts' xs 0

#+end_src

** Exercise 4

Write a function that computes the mean of a list.

#+begin_src

getAvg :: (Fractional a) => [a] -> a
getAvg xs = sum xs / (fromIntegral (length xs))

getAvg []
-- NaN

getAvg [1..3]
-- 2.0

getAvg [1..10]
-- 5.5

#+end_src

** Exercise 5

Write a function that turns a list into palindrome, e.g. '[1, 2, 3]' becomes '[1, 2, 3, 3, 2, 1]'

#+begin_src

list2palindrome :: [a] -> [a]
list2palindrome xs = xs ++ reverse xs

list2palindrome [1..3]
-- [1,2,3,3,2,1]

list2palindrome ['a'..'d']
-- "abcddcba"

#+end_src

** Exercise 6

Write a function that determines if a list is a palindrome.

#+begin_src

isPalindrome :: Eq a => [a] -> Bool
isPalindrome xs = xs == reverse xs

isPalindrome (list2palindrome ['a'..'d'])
-- True
isPalindrome (init (list2palindrome ['a'..'d']))
-- False

#+end_src

** Exercise 7

Use 'sortBy' from 'Data.List' to sort a list of lists based on the length of
each sublist.

#+begin_src

import           Data.List (sortBy)

compareLengths :: [a] -> [b] -> Ordering
compareLengths xs ys = compare (length xs) (length ys)

sortBy compareLengths [[1, 2, 3], [1], [1, 2]]
- [[1], [1,2], [1,2,3]]

#+end_src
