#+title: Ch03
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Defining Types, Streamlining Functions
* Defining New Data Type

#+begin_src

data BookInfo = Book Int String [String] deriving (Show)
-- Book iD title authors

#+end_src

'BookInfo' - name of new type (a type constructor)
'Book' - name of a value constructor

value constructor and type constructor often have the same name

Once new type was defined we can inspect it in GHCI

#+begin_src

:t BookInfo
-- or
:t Book 1 "title" ["author 1", "author 2"]

#+end_src

* Type Synonyms

#+begin_src

type CustormerID = Int
type Name = String

-- which can now be used in

data Customer = Customer CustomerID Name

#+end_src

* Algebraic Data Types (ADTs)

#+begin_src

data Bool = False | True
-- a type with two value constructors
-- it can be either (| - or) one of the value constructors

#+end_src

* ADTs vs Tuples

ADTs allow to distinguish between otherwise identical pieces of information,
e.g.

#+begin_src

type CustormerID = Int
type Name = String
data Customer = Customer CustomerID Name

customer = Customer 2 "John Smith"

-- vs

customer = (2, "John Smith")

#+end_src

The above properties of ADTs help to reduce the number of mistakes in the code.

* Structures

#+begin_src

// c example
struct book_info {
    int id;
    char *title;
    char **authors;
}

-- hs equivalent
data BookInfo = Book Int String [String]
                deriving (Show)

-- hs equivalent (Record Syntax)
data BookInfor = Book {
     id :: Int,
     title :: String,
     authors :: [String]
     } deriving (Show)

#+end_src

* Enums

#+begin_src

enum Color = Red | Green | Blue  deriving (Eq, Show)

Red == Green
-- False

Blue == Blue
-- True

#+end_src

* Pattern Matching

#+begin_src

mySum :: Num a => [a] -> a
mySum []     = 0
mySum (x:xs) = x + mySum xs

#+end_src

It works because a list, e.g.

- '[1, 2, 3]' is actually '(1:(2:(3:[])))', so '1' is 'x' and (2:(3:[])) is 'xs'
- '[1, 2]' is actually '(1:(2:[]))', so '1' is 'x' and '(2:[])' is 'xs'
- '[1]' is actually '(1:[])', so '1' is 'x' and '[]' is 'xs',
  etc.

  Patterns are matched in the order from top to bottom.

* Construction and Deconstruction

Construction is when we apply some values to constructor, e.g. 'Just 1.25'.

Deconstruction is when we pattern match against the constructor, e.g in a
function. The initial value/variable is not destroyed (it's just the name).

#+begin_src

x = Just 1.25
y = Nothing

extract :: Maybe a -> a -> a
extract (Just x) _  = x
extract Nothing def = def

extract x 0.0
-- 1.25

x
-- Just 1.25

extract y 0.0
-- 0.0

y
-- Nothing
#+end_src

* Naming in Patterns

'a', 'b' - is common in function signature

'(x:xs)' is common in function body

'_' - wild card pattern is common in function body for the part we don't care
about

* Exclusiveness

The patterns should be exclusive or they may be an error, e.g. like in the non
exclusive pattern below:

#+begin_src

mySum :: Num a => [a] -> a
-- mySum []     = 0
mySum (x:xs) = x + mySum xs

#+end_src
