#+title: Ch04
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Functional Programming
** Universal Split Lines

Below a universal 'splitLines' that should act cross platforms regardless of
the type of line terminators ('\n' vs. '\r\n'). Notice that the built-in 'lines'
works well only on '\n' line separators (prevalent in Unix-like systems).

#+begin_src

-- break is built-in
:t break
-- break :: (a -> Bool) -> [a] -> ([a], [a])

break odd [2, 1, 4, 3, 6]
-- ([2],[1,4,3,6])

isLineTerminator :: Char -> Bool
isLineTerminator c = c == 'r' || c == '\n'

splitLines :: String -> [String]
splitLines [] = []
splitLines cs =
  let (pre, suf) = break isLineTerminator cs
  in pre : case suf of
    ('\r' : '\n' : rest) -> splitLines rest
    ('\r' : rest)        -> splitLines rest
    ('\n' : rest)        -> splitLines rest
    _                    -> []

#+end_src

** Infix Functions

By default all the functions in Haskell are infix (or prefix) functions.
To change it use back-ticks, e.g.

#+begin_src

elem 'a' ['a'..'d']
-- True

'a' `elem` ['a'..'d']
-- True

#+end_src

** Working with Lists

Common and useful functions operating on lists:

- 'length'
- 'null' (kind of 'isempty' in other programming languages)
- 'head' and 'last' (returns first and last elt)
- 'init' and 'tail' (returns all but last, and all but first element)

** Partial and Total Functions

Functions with only some of its arguments applied are partial function.
Functions with all arguments applied and clear input-output mapping are total functions.

** Simple List Manipulations

#+begin_src

:t (++)
-- (++) :: [a] -> [a] -> [a]

:t concat
-- concat :: [[a]] -> [a]

:t reverse
-- reverse :: [a] -> [a]

:t and
-- and :: [Bool] -> Bool

:t or
-- or :: [Bool] -> Bool

:t all
-- all :: (a -> Bool) -> [a] -> Bool

:t any
-- any :: (a -> Bool) -> [a] -> Bool

#+end_src

My implementations for practice:

Version of '++':

#+begin_src

-- (++), PP - plus plus
myPP :: [a] -> [a] -> [a]
myPP [] ys     = ys
myPP [x] ys    = x : ys
myPP (x:xs) ys = x : myPP xs ys

myPP "hello, " "world"
-- "hello, world"

#+end_src


Version of 'concat':

#+begin_src

-- concat
myConcat :: [[a]] -> [a]
myConcat ([])   = []
myConcat (x:xs) = myPP x (myConcat xs)

-- or
myConcat :: [[a]] -> [a]
myConcat ([])   = []
myConcat (x:xs) = x ++ myConcat xs

myConcat [[1..3], [4..5]]
-- [1,2,3,4,5]

myConcat [[1..3], [4..5], [6..7]]
-- [1,2,3,4,5,6,7]

myConcat [[1..3], [], [6..7]]
-- [1,2,3,6,7]

#+end_src

Version of 'reverse':

#+begin_src

myReverse :: [a] -> [a]
myReverse []     = []
myReverse (x:xs) = myReverse xs ++ [x]

#+end_src

Version of 'and':

#+begin_src

myAnd :: [Bool] -> Bool
myAnd []         = True
myAnd (False:xs) = False
myAnd (True:xs)  = myAnd xs

-- or

myAnd :: [Bool] -> Bool
myAnd []         = True
myAnd (False:_) = False
myAnd (True:xs)  = myAnd xs

#+end_src

Version of 'or':

#+begin_src

myOr :: [Bool] -> Bool
myOr []         = False
myOr (False:xs) = myOr xs
myOr (True:xs)  = True

-- or

myOr :: [Bool] -> Bool
myOr []         = False
myOr (False:xs) = myOr xs
myOr (True:_)  = True

#+end_src

Version of 'all':

#+begin_src

myAll :: (a -> Bool) -> [a] -> Bool
myAll _ []     = True
myAll f (x:xs) = if f x
  then myAll f xs
  else False

myAll odd []
-- True
myAll odd [1,3..21]
-- True
myAll odd ([1,3..21] ++ [10])
-- False

#+end_src

Version of 'any:

#+begin_src

myAny :: (a -> Bool) -> [a] -> Bool
myAny _ [] = False
myAny f (x:xs) = if f x
  then True
  else myAny f xs

myAny odd []
-- False
myAny odd [2,4..100]
-- False
myAny odd ([2,4..100] ++ [1])
-- True

#+end_src

** Working with Sublists

#+begin_src

:t take
-- take :: Int -> [a] -> [a]

:t drop
-- drop :: Int -> [a] -> [a]

:t splitAt
-- splitAt :: Int -> [a] -> ([a], [a])

:t takeWhile
-- takeWhile :: (a -> Bool) -> [a] -> [a]

:t dropWhile
-- dropWhile :: (a -> Bool) -> [a] -> [a]

:t span
-- span :: (a -> Bool) -> [a] -> ([a], [a])

:t break
-- break :: (a -> Bool) -> [a] -> ([a], [a])

#+end_src

My implementations for practice:

Version of 'take':

#+begin_src

myTake :: Int -> [a] -> [a]
myTake 0 _      = []
myTake n (x:xs) = x : myTake (n-1) xs

-- or more robust

myTake :: Int -> [a] -> [a]
myTake n (x:xs) | n <= 0 = []
                | otherwise = x : myTake (n-1) xs

#+end_src

Version of 'drop':

#+begin_src

myDrop :: Int -> [a] -> [a]
myDrop 0 xs     = xs
myDrop n (x:xs) = myDrop (n-1) xs

-- or more robust

myDrop :: Int -> [a] -> [a]
myDrop n (x:xs)     | n <= 0 = x : xs
                    | otherwise = myDrop (n-1) xs

#+end_src

Version of 'splitAt':

#+begin_src

mySplitAt :: Int -> [a] -> ([a], [a])
mySplitAt n xs = ((take n xs), (drop n xs))

mySplitAt 5 "hellothere"
-- ("hello","there")

#+end_src

Version of 'takeWhile':

#+begin_src

myTakeWhile :: (a -> Bool) -> [a] -> [a]
myTakeWhile _ []        = []
myTakeWhile pred (x:xs) = if pred x
  then x : myTakeWhile pred xs
  else []

-- or

myTakeWhile :: (a -> Bool) -> [a] -> [a]
myTakeWhile _ []        = []
myTakeWhile pred (x:xs)
  | pred x = x : myTakeWhile pred xs
  | otherwise = []

myTakeWhile odd [1..10]
-- [1]

myTakeWhile odd [1, 3, 4, 5]
-- [1,3]

#+end_src

Version of 'span':

#+begin_src

mySpan' :: (a -> Bool) -> [a] -> ([a], [a]) -> ([a], [a])
mySpan' _ [] acc     = acc
mySpan' pred (x:xs) (ys, zs)
  | pred x = mySpan' pred xs (x:ys, zs)
  | otherwise = (reverse ys, x:xs ++ zs)

mySpan :: (a -> Bool) -> [a] -> ([a], [a])
mySpan pred xs = mySpan' pred xs ([], [])

mySpan even [2,4,9,10,11]
-- ([2,4], [9,10,11])

mySpan even [1, 2,4, 10,11]
([], [1,2,4,10,11])

#+end_src

Version of 'break':

#+begin_src

myBreak' :: (a -> Bool) -> [a] -> ([a], [a]) -> ([a], [a])
myBreak' _ [] acc     = acc
myBreak' pred (x:xs) (ys, zs)
  | pred x = (reverse ys, x:xs ++ zs)
  | otherwise = myBreak' pred xs (x:ys, zs)

myBreak :: (a -> Bool) -> [a] -> ([a], [a])
myBreak pred xs = myBreak' pred xs ([], [])

myBreak even [1,3,4,6,7,8]
-- ([1,3], [4,6,7,8])

myBreak odd [1,3,4,6,7,8]
-- ([], [1,3,4,6,7,8])

myBreak even [1,3..9]
--- ([9,7,5,3,1],[])

#+end_src

** Searching Lists

#+begin_src

:t elem
-- elem :: (Eq a) => a -> [a] -> Bool

:t notElem
-- notElem :: (Eq a) => a -> [a] -> Bool

:t filter
-- filter :: (a -> Bool) -> [a] -> [a]

#+end_src

My implementations for practice:

Version of 'elem':

#+begin_src

myElem :: (Eq a) => a -> [a] -> Bool
myElem _ [] = False
myElem x (y:ys)
  | x == y = True
  | otherwise = myElem x ys

#+end_src

Version of 'notElem':

#+begin_src

myNotElem :: (Eq a) => a -> [a] -> Bool
myNotElem _ [] = True
myNotElem x (y:ys)
  | x == y = False
  | otherwise = myNotElem x ys

#+end_src

Version of 'filter':

#+begin_src

myFilter :: (a -> Bool) -> [a] -> [a]
myFilter _ [] = []
myFilter pred (x:xs)
  | pred x = x : myFilter pred xs
  | otherwise = myFilter pred xs

#+end_src

Other useful fns working on lists.

#+begin_src

:module +Data.List

:t isPrefixOf
-- isPrefixOf :: Eq a => [a] -> [a] -> Bool

:t isInfixOf
-- isInfixOf :: Eq a => [a] -> [a] -> Bool

:t isSuffixOf
-- isSuffixOf :: Eq a => [a] -> [a] -> Bool

#+end_src

Version of 'isPrefixOf':

#+begin_src

myIsPrefixOf :: Eq a => [a] -> [a] -> Bool
myIsPrefixOf [] _ = True
myIsPrefixOf _ [] = False
myIsPrefixOf (x:xs) (y:ys)
  | x == y = myIsPrefixOf xs ys
  | otherwise = False

#+end_src

Version of 'isInfixOf':

#+begin_src

myIsInfixOf' :: Eq a => [a] -> [a] -> Bool -> Bool
myIsInfixOf' [] _ _ = True
myIsInfixOf' _ [] prevCharMatch = prevCharMatch
myIsInfixOf' (x:xs) (y:ys) prevCharMatch
  | x == y = myIsInfixOf' xs ys True
  | x /= y && prevCharMatch = False
  | otherwise = myIsInfixOf' (x:xs) ys False

myIsInfixOf :: Eq a => [a] -> [a] -> Bool
myIsInfixOf xs ys = myIsInfixOf' xs ys False

-- or
myIsInfixOf :: Eq a => [a] -> [a] -> Bool
myIsInfixOf xs [] = myIsPrefixOf xs []
myIsInfixOf xs ys = (myIsPrefixOf xs ys) || myIsInfixOf xs (tail ys)

map (isInfixOf "la") ["", "axxlxa", "trela", "trala", "lana"]
-- [False,False,True,True,True]

map (myIsInfixOf "la") ["", "axxlxa", "trela", "trala", "lana"]
-- [False,False,True,True,True]

#+end_src

Version of 'isSuffixOf':

#+begin_src

myIsSuffixOf :: Eq a => [a] -> [a] -> Bool
myIsSuffixOf xs ys = myIsPrefixOf (reverse xs) (reverse ys)

#+end_src

** Working with Sevelar Lists

This is to be done with:

#+begin_src

:t zip
-- zip :: [a] -> [b] -> [(a, b)]

:t zipWith
-- zipWith :: (a -> b -> c) -> [a] -> [b] -> [c]

#+end_src

My implementations for practice:

Version of 'zip':

#+begin_src

myZip :: [a] -> [b] -> [(a, b)]
myZip [] _          = []
myZip _ []          = []
myZip (x:xs) (y:ys) = (x, y) : myZip xs ys

myZip [1..5] ['a'..]
-- [(1,'a'),(2,'b'),(3,'c'),(4,'d'),(5,'e')]

#+end_src

Version of 'zipWith':

#+begin_src

myZipWith :: (a -> b -> c) -> [a] -> [b] -> [c]
myZipWith _ [] _          = []
myZipWith _ _ []          = []
myZipWith f (x:xs) (y:ys) = (f x y) : myZipWith f xs ys

myZipWith (+) [1..9] [10,20..]
-- [11,22,33,44,55,66,77,88,99]

#+end_src

** Special String Functions

#+begin_src

:t lines
-- lines :: String -> [String]

:t unlines
-- unlines :: [String] -> String

:t words
-- words :: String -> [String]

:t unwords
-- unwords :: [String] -> String

#+end_src

** Exercises
*** Exercise 1

Write 'safe' versions of the following functions: 'head', 'tail', 'last',
'init'. The functions signatures are:

#+begin_src

safeHead :: [a] -> Maybe a
safeTail :: [a] -> Maybe [a]
safeLast :: [a] -> Maybe a
safeInit :: [a] -> Maybe [a]

#+end_src>

#+begin_src

safeHead :: [a] -> Maybe a
safeHead []     = Nothing
safeHead (x:_) = Just x
-- or: safeHead (x:xs) = Just x

safeTail :: [a] -> Maybe [a]
safeTail []     = Nothing
safeTail (_:xs) = Just xs
-- or: safeTail (x:xs) = Just xs

#+end_src>

#+begin_src

safeLast :: [a] -> Maybe a
safeLast []     = Nothing
safeLast [x]    = Just x
safeLast (x:xs) = safeLast xs

#+end_src>
