#+title: Ch04
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Functional Programming
* Universal Split Lines

Below a universal 'splitLines' that should act cross platforms regardless of
the type of line terminators ('\n' vs. '\r\n'). Notice that the built-in 'lines'
works well only on '\n' line separators (prevalent in Unix-like systems).

#+begin_src

-- break is built-in
:t break
-- break :: (a -> Bool) -> [a] -> ([a], [a])

break odd [2, 1, 4, 3, 6]
-- ([2],[1,4,3,6])

isLineTerminator :: Char -> Bool
isLineTerminator c = c == 'r' || c == '\n'

splitLines :: String -> [String]
splitLines [] = []
splitLines cs =
  let (pre, suf) = break isLineTerminator cs
  in pre : case suf of
    ('\r' : '\n' : rest) -> splitLines rest
    ('\r' : rest)        -> splitLines rest
    ('\n' : rest)        -> splitLines rest
    _                    -> []

#+end_src

* Infix Functions

By default all the functions in Haskell are infix (or prefix) functions.
To change it use back-ticks, e.g.

#+begin_src

elem 'a' ['a'..'d']
-- True

'a' `elem` ['a'..'d']
-- True

#+end_src

* Working with Lists

Common and useful functions operating on lists:

- 'length'
- 'null' (kind of 'isempty' in other programming languages)
- 'head' and 'last' (returns first and last elt)
- 'init' and 'tail' (returns all but last, and all but first element)

* Partial and Total Functions

Functions with only some of its arguments applied are partial function.
Functions with all arguments applied and clear input-output mapping are total functions.

* Simple List Manipulations

#+begin_src

:t (++)
-- (++) :: [a] -> [a] -> [a]

:t concat
-- concat :: [[a]] -> [a]

:t reverse
-- reverse :: [a] -> [a]

:t and
-- and :: [Bool] -> Bool

:t or
-- or :: [Bool] -> Bool

:t all
-- all :: (a -> Bool) -> [a] -> Bool

:t any
-- any :: (a -> Bool) -> [a] -> Bool

#+end_src

* Working with Sublists

#+begin_src

:t take
-- take :: Int -> [a] -> [a]

:t drop
-- drop :: Int -> [a] -> [a]

:t splitAt
-- splitAt :: Int -> [a] -> ([a], [a])

:t takeWhile
-- takeWhile :: (a -> Bool) -> [a] -> [a]

:t dropWhile
-- dropWhile :: (a -> Bool) -> [a] -> [a]

:t span
-- span :: (a -> Bool) -> [a] -> ([a], [a])

:t break
-- break :: (a -> Bool) -> [a] -> ([a], [a])

#+end_src
