#+title: Ch04
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* Functional Programming
** Universal Split Lines

Below a universal 'splitLines' that should act cross platforms regardless of
the type of line terminators ('\n' vs. '\r\n'). Notice that the built-in 'lines'
works well only on '\n' line separators (prevalent in Unix-like systems).

#+begin_src

-- break is built-in
:t break
-- break :: (a -> Bool) -> [a] -> ([a], [a])

break odd [2, 1, 4, 3, 6]
-- ([2],[1,4,3,6])

isLineTerminator :: Char -> Bool
isLineTerminator c = c == 'r' || c == '\n'

splitLines :: String -> [String]
splitLines [] = []
splitLines cs =
  let (pre, suf) = break isLineTerminator cs
  in pre : case suf of
    ('\r' : '\n' : rest) -> splitLines rest
    ('\r' : rest)        -> splitLines rest
    ('\n' : rest)        -> splitLines rest
    _                    -> []

#+end_src

** Infix Functions

By default all the functions in Haskell are infix (or prefix) functions.
To change it use back-ticks, e.g.

#+begin_src

elem 'a' ['a'..'d']
-- True

'a' `elem` ['a'..'d']
-- True

#+end_src

** Working with Lists

Common and useful functions operating on lists:

- 'length'
- 'null' (kind of 'isempty' in other programming languages)
- 'head' and 'last' (returns first and last elt)
- 'init' and 'tail' (returns all but last, and all but first element)

** Partial and Total Functions

Functions with only some of its arguments applied are partial function.
Functions with all arguments applied and clear input-output mapping are total functions.

** Simple List Manipulations

#+begin_src

:t (++)
-- (++) :: [a] -> [a] -> [a]

:t concat
-- concat :: [[a]] -> [a]

:t reverse
-- reverse :: [a] -> [a]

:t and
-- and :: [Bool] -> Bool

:t or
-- or :: [Bool] -> Bool

:t all
-- all :: (a -> Bool) -> [a] -> Bool

:t any
-- any :: (a -> Bool) -> [a] -> Bool

#+end_src

My implementations for practice:

Version of '++':

#+begin_src

-- (++), PP - plus plus
myPP :: [a] -> [a] -> [a]
myPP [] ys     = ys
myPP [x] ys    = x : ys
myPP (x:xs) ys = x : myPP xs ys

myPP "hello, " "world"
-- "hello, world"

#+end_src


Version of 'concat':

#+begin_src

-- concat
myConcat :: [[a]] -> [a]
myConcat ([])   = []
myConcat (x:xs) = myPP x (myConcat xs)

-- or
myConcat :: [[a]] -> [a]
myConcat ([])   = []
myConcat (x:xs) = x ++ myConcat xs

myConcat [[1..3], [4..5]]
-- [1,2,3,4,5]

myConcat [[1..3], [4..5], [6..7]]
-- [1,2,3,4,5,6,7]

myConcat [[1..3], [], [6..7]]
-- [1,2,3,6,7]

#+end_src

Version of 'reverse':

#+begin_src

myReverse :: [a] -> [a]
myReverse []     = []
myReverse (x:xs) = myReverse xs ++ [x]

#+end_src

Version of 'and':

#+begin_src

myAnd :: [Bool] -> Bool
myAnd []         = True
myAnd (False:xs) = False
myAnd (True:xs)  = myAnd xs

-- or

myAnd :: [Bool] -> Bool
myAnd []         = True
myAnd (False:_) = False
myAnd (True:xs)  = myAnd xs

#+end_src

Version of 'or':

#+begin_src

myOr :: [Bool] -> Bool
myOr []         = False
myOr (False:xs) = myOr xs
myOr (True:xs)  = True

-- or

myOr :: [Bool] -> Bool
myOr []         = False
myOr (False:xs) = myOr xs
myOr (True:_)  = True

#+end_src

Version of 'all':

#+begin_src

myAll :: (a -> Bool) -> [a] -> Bool
myAll _ []     = True
myAll f (x:xs) = if f x
  then myAll f xs
  else False

myAll odd []
-- True
myAll odd [1,3..21]
-- True
myAll odd ([1,3..21] ++ [10])
-- False

#+end_src

Version of 'any:

#+begin_src

myAny :: (a -> Bool) -> [a] -> Bool
myAny _ [] = False
myAny f (x:xs) = if f x
  then True
  else myAny f xs

myAny odd []
-- False
myAny odd [2,4..100]
-- False
myAny odd ([2,4..100] ++ [1])
-- True

#+end_src

** Working with Sublists

#+begin_src

:t take
-- take :: Int -> [a] -> [a]

:t drop
-- drop :: Int -> [a] -> [a]

:t splitAt
-- splitAt :: Int -> [a] -> ([a], [a])

:t takeWhile
-- takeWhile :: (a -> Bool) -> [a] -> [a]

:t dropWhile
-- dropWhile :: (a -> Bool) -> [a] -> [a]

:t span
-- span :: (a -> Bool) -> [a] -> ([a], [a])

:t break
-- break :: (a -> Bool) -> [a] -> ([a], [a])

#+end_src

My implementations for practice:

Version of 'take':

#+begin_src

myTake :: Int -> [a] -> [a]
myTake 0 _      = []
myTake n (x:xs) = x : myTake (n-1) xs

-- or more robust

myTake :: Int -> [a] -> [a]
myTake n (x:xs) | n <= 0 = []
                | otherwise = x : myTake (n-1) xs

#+end_src

Version of 'drop':

#+begin_src

myDrop :: Int -> [a] -> [a]
myDrop 0 xs     = xs
myDrop n (x:xs) = myDrop (n-1) xs

-- or more robust

myDrop :: Int -> [a] -> [a]
myDrop n (x:xs)     | n <= 0 = x : xs
                    | otherwise = myDrop (n-1) xs

#+end_src

Version of 'splitAt':

#+begin_src

mySplitAt :: Int -> [a] -> ([a], [a])
mySplitAt n xs = ((take n xs), (drop n xs))

mySplitAt 5 "hellothere"
-- ("hello","there")

#+end_src

Version of 'takeWhile':

#+begin_src

myTakeWhile :: (a -> Bool) -> [a] -> [a]
myTakeWhile _ []        = []
myTakeWhile pred (x:xs) = if pred x
  then x : myTakeWhile pred xs
  else []

-- or

myTakeWhile :: (a -> Bool) -> [a] -> [a]
myTakeWhile _ []        = []
myTakeWhile pred (x:xs)
  | pred x = x : myTakeWhile pred xs
  | otherwise = []

myTakeWhile odd [1..10]
-- [1]

myTakeWhile odd [1, 3, 4, 5]
-- [1,3]

#+end_src

Version of 'span':

#+begin_src

mySpan' :: (a -> Bool) -> [a] -> ([a], [a]) -> ([a], [a])
mySpan' _ [] acc     = acc
mySpan' pred (x:xs) (ys, zs)
  | pred x = mySpan' pred xs (x:ys, zs)
  | otherwise = (reverse ys, x:xs ++ zs)

mySpan :: (a -> Bool) -> [a] -> ([a], [a])
mySpan pred xs = mySpan' pred xs ([], [])

mySpan even [2,4,9,10,11]
-- ([2,4], [9,10,11])

mySpan even [1, 2,4, 10,11]
([], [1,2,4,10,11])

#+end_src

Version of 'break':

#+begin_src

myBreak' :: (a -> Bool) -> [a] -> ([a], [a]) -> ([a], [a])
myBreak' _ [] acc     = acc
myBreak' pred (x:xs) (ys, zs)
  | pred x = (reverse ys, x:xs ++ zs)
  | otherwise = myBreak' pred xs (x:ys, zs)

myBreak :: (a -> Bool) -> [a] -> ([a], [a])
myBreak pred xs = myBreak' pred xs ([], [])

myBreak even [1,3,4,6,7,8]
-- ([1,3], [4,6,7,8])

myBreak odd [1,3,4,6,7,8]
-- ([], [1,3,4,6,7,8])

myBreak even [1,3..9]
--- ([9,7,5,3,1],[])

#+end_src

** Searching Lists

#+begin_src

:t elem
-- elem :: (Eq a) => a -> [a] -> Bool

:t notElem
-- notElem :: (Eq a) => a -> [a] -> Bool

:t filter
-- filter :: (a -> Bool) -> [a] -> [a]

#+end_src

My implementations for practice:

Version of 'elem':

#+begin_src

myElem :: (Eq a) => a -> [a] -> Bool
myElem _ [] = False
myElem x (y:ys)
  | x == y = True
  | otherwise = myElem x ys

#+end_src

Version of 'notElem':

#+begin_src

myNotElem :: (Eq a) => a -> [a] -> Bool
myNotElem _ [] = True
myNotElem x (y:ys)
  | x == y = False
  | otherwise = myNotElem x ys

#+end_src

Version of 'filter':

#+begin_src

myFilter :: (a -> Bool) -> [a] -> [a]
myFilter _ [] = []
myFilter pred (x:xs)
  | pred x = x : myFilter pred xs
  | otherwise = myFilter pred xs

#+end_src

Other useful fns working on lists.

#+begin_src

:module +Data.List

:t isPrefixOf
-- isPrefixOf :: Eq a => [a] -> [a] -> Bool

:t isInfixOf
-- isInfixOf :: Eq a => [a] -> [a] -> Bool

:t isSuffixOf
-- isSuffixOf :: Eq a => [a] -> [a] -> Bool

#+end_src

Version of 'isPrefixOf':

#+begin_src

myIsPrefixOf :: Eq a => [a] -> [a] -> Bool
myIsPrefixOf [] _ = True
myIsPrefixOf _ [] = False
myIsPrefixOf (x:xs) (y:ys)
  | x == y = myIsPrefixOf xs ys
  | otherwise = False

#+end_src

Version of 'isInfixOf':

#+begin_src

myIsInfixOf' :: Eq a => [a] -> [a] -> Bool -> Bool
myIsInfixOf' [] _ _ = True
myIsInfixOf' _ [] prevCharMatch = prevCharMatch
myIsInfixOf' (x:xs) (y:ys) prevCharMatch
  | x == y = myIsInfixOf' xs ys True
  | x /= y && prevCharMatch = False
  | otherwise = myIsInfixOf' (x:xs) ys False

myIsInfixOf :: Eq a => [a] -> [a] -> Bool
myIsInfixOf xs ys = myIsInfixOf' xs ys False

-- or
myIsInfixOf :: Eq a => [a] -> [a] -> Bool
myIsInfixOf xs [] = myIsPrefixOf xs []
myIsInfixOf xs ys = (myIsPrefixOf xs ys) || myIsInfixOf xs (tail ys)

map (isInfixOf "la") ["", "axxlxa", "trela", "trala", "lana"]
-- [False,False,True,True,True]

map (myIsInfixOf "la") ["", "axxlxa", "trela", "trala", "lana"]
-- [False,False,True,True,True]

#+end_src

Version of 'isSuffixOf':

#+begin_src

myIsSuffixOf :: Eq a => [a] -> [a] -> Bool
myIsSuffixOf xs ys = myIsPrefixOf (reverse xs) (reverse ys)

#+end_src

** Working with Sevelar Lists

This is to be done with:

#+begin_src

:t zip
-- zip :: [a] -> [b] -> [(a, b)]

:t zipWith
-- zipWith :: (a -> b -> c) -> [a] -> [b] -> [c]

#+end_src

My implementations for practice:

Version of 'zip':

#+begin_src

myZip :: [a] -> [b] -> [(a, b)]
myZip [] _          = []
myZip _ []          = []
myZip (x:xs) (y:ys) = (x, y) : myZip xs ys

myZip [1..5] ['a'..]
-- [(1,'a'),(2,'b'),(3,'c'),(4,'d'),(5,'e')]

#+end_src

Version of 'zipWith':

#+begin_src

myZipWith :: (a -> b -> c) -> [a] -> [b] -> [c]
myZipWith _ [] _          = []
myZipWith _ _ []          = []
myZipWith f (x:xs) (y:ys) = (f x y) : myZipWith f xs ys

myZipWith (+) [1..9] [10,20..]
-- [11,22,33,44,55,66,77,88,99]

#+end_src

** Special String Functions

#+begin_src

:t lines
-- lines :: String -> [String]

:t unlines
-- unlines :: [String] -> String

:t words
-- words :: String -> [String]

:t unwords
-- unwords :: [String] -> String

#+end_src

** Exercises
*** Exercise 1

Write 'safe' versions of the following functions: 'head', 'tail', 'last',
'init'. The functions signatures are:

#+begin_src

safeHead :: [a] -> Maybe a
safeTail :: [a] -> Maybe [a]
safeLast :: [a] -> Maybe a
safeInit :: [a] -> Maybe [a]

#+end_src>

#+begin_src

safeHead :: [a] -> Maybe a
safeHead []     = Nothing
safeHead (x:_) = Just x
-- or: safeHead (x:xs) = Just x

safeTail :: [a] -> Maybe [a]
safeTail []     = Nothing
safeTail (_:xs) = Just xs
-- or: safeTail (x:xs) = Just xs

#+end_src>

#+begin_src

safeLast :: [a] -> Maybe a
safeLast []     = Nothing
safeLast [x]    = Just x
safeLast (x:xs) = safeLast xs

#+end_src>

#+begin_src

safeInit :: [a] -> Maybe [a]
safeInit []     = Nothing
safeInit (x:xs) = Just xs

#+end_src>

*** Exercise 2

Write a function 'splitWith' that acts similarly to 'words', and has a following signature.

#+begin_src

splitWith :: (a -> Bool) -> [a] -> [[a]]

#+end_src

Exemplary solution:

#+begin_src

splitWith' :: (a -> Bool) -> [a] -> [a] -> [[a]]
splitWith' _ [] acc = (reverse acc) : []
splitWith' pred (x:xs) acc
  | pred x =
    if null acc then splitWith' pred xs []
    else (reverse acc) : (splitWith' pred xs [])
  | otherwise = splitWith' pred xs (x : acc)

splitWith :: (a -> Bool) -> [a] -> [[a]]
splitWith pred xs = splitWith' pred xs []

splitWith (== ' ') "ala ma   kota"
-- ["ala","ma","kota"]

words "ala ma   kota"
-- ["ala","ma","kota"]

isBreak :: Char -> Bool
isBreak x = x == ' ' || x == '\n' || x == '\t'

splitWith isBreak "ala \tma   kota\na tomek psa"
-- ["ala","ma","kota","a","tomek","psa"]

words "ala \tma   kota\na tomek psa"
-- ["ala","ma","kota","a","tomek","psa"]

#+end_src

*** Exercise 3

Use the framework from the previous snippets to write a program that prints the
first word of each line of its input.

#+begin_src

-- file: printFirstWordOfEachLine.hs

getFirstWord :: String -> String
getFirstWord lineOfTxt = head (words lineOfTxt)

getFirstWords :: String -> [String]
getFirstWords input = map getFirstWord (lines input)

handleInput :: String -> String
handleInput input = unlines (getFirstWords input)

main :: IO ()
main = do
  interact handleInput

#+end_src

#+begin_src

-- in shell
ghc printFirstWordOfEachLine.hs

-- and
./printFirstWordOfEachLine < test.txt

#+end_src

or

#+begin_src

-- in shell
runghc printFirstWordOfEachLine.hs < test.txt

#+end_src

*** Exercise 4

Write a program that transpose the text in a file, e.g.

#+begin_src

transpose "hello\nworld\n"
-- "hw\neo\nlr\nll\nod\n"

-- or
transpose "hello\nworld\n"
-- hw
-- eo
-- lr
-- ll
-- od

#+end_src

My note: the task description is not clear. For instance, it is unknown what
should be done if the lines are of different length. So, I'll just do whatever
comes to my mind and/or will be convenient to me.

#+begin_src

-- file: transposeLines.hs

transposeLines :: [String] -> [String]
transposeLines xs -- xs are lines of text
  | any null xs = []
  | otherwise = (map head xs) : transposeLines (map tail xs)

handleInput :: String -> String
handleInput input = unlines (transposeLines (lines input))

main :: IO ()
main = do
  interact handleInput

#+end_src

#+begin_src

-- in shell
ghc transposeLines.hs

-- and
./transposeLines < test.txt

#+end_src

or

#+begin_src

-- in shell
runghc transposeLines.hs < test.txt

#+end_src

*** Exercise 5

Use a fold to rewrite 'asInt'. Expected behavior:

#+begin_src

asInt "101"
-- 101

asInt "-333"
-- -333

asInt "1410"
-- 1410

#+end_src

Solution:

#+begin_src

import Data.Char (digitToInt)

char2Int :: Int -> Char -> Int
char2Int acc c = acc * 10 + digitToInt c

converter :: String -> Int
converter = foldl char2Int 0

asInt :: String -> Int
asInt (y:ys)
  | y == '-' = negate (converter ys)
  | otherwise = converter (y:ys)

#+end_src

Or using closures (function definitions inside a function):

#+begin_src

import data.char (digittoint)

asInt :: String -> Int
asInt (y:ys)
  | y == '-' = negate (converter ys)
  | otherwise = converter (y:ys)
  where char2Int :: Int -> Char -> Int
        char2Int acc c = acc * 10 + digitToInt c
        converter :: String -> Int
        converter = foldl char2Int 0

#+end_src

*** Exercise 6

Write a version of 'concat' function using 'foldr'.

#+begin_src

myConcat :: [[a]] -> [a]
myConcat xxs = foldr (++) [] xxs

#+end_src

*** Exercise 7

Write a version of 'group' function.

#+begin_src

:m Data.List

:t group
-- group :: Eq a => [a] -> [[a]]

group [1,1,1,3,2,2,1,1,1]
-- [[1,1,1],[3],[2,2],[1,1,1]]

#+end_src

Solution:

#+begin_src

myGroup' :: Eq a => [a] -> ([a], [a])
myGroup' xs = (takeWhile (== (head xs)) xs,
               dropWhile (== (head xs)) xs)

-- or
myGroup' :: Eq a => [a] -> ([a], [a])
myGroup' ys@(x:_) = (takeWhile (==x) ys,
                     dropWhile (==x) ys)

myGroup :: Eq a => [a] -> [[a]]
myGroup [] = []
myGroup xs = fstGroup : myGroup rest
  where (fstGroup, rest) = myGroup' xs

#+end_src

*** Exercise 8

Rewrite a version of 'any' with a 'fold':

#+begin_src

:t any
-- any :: (a -> Bool) -> [a] -> Bool

#+end_src

Solution to 'any' with a 'fold':

#+begin_src

myAny :: (a -> Bool) -> [a] -> Bool
myAny pred xs = foldr (\x acc -> if pred x then True else acc) False xs

#+end_src

*** Exercise 9

Write a version of 'cycle':

#+begin_src

:t cycle
cycle :: [a] -> [a]

#+end_src

Solution:

#+begin_src

myCycle :: [a] -> [a]
myCycle xs = xs ++ myCycle xs

#+end_src

** Loops. Explicit Recursion

Example 1.

#+begin_src

// C
int as_int(char *str) {
    int acc;

    for (acc = 0; isdigit(*str); str++) {
        acc = acc * 10 + (*str - '0');
    }
    return acc;
}

#+end_src


#+begin_src

-- hs

import Data.Char (digitToInt)

loop :: Int -> String -> Int
loop acc [] = acc
loop acc (x:xs) = loop updatedAcc xs
  where updatedAcc = acc * 10 + digitToInt x

asInt :: String -> Int
asInt xs = loop 0 xs

#+end_src

Example 2.

#+begin_src

// C
void square(double *out, const double *in, size_t length) {
    for (size_t i = 0; i < length; i++) {
        out[i] = in[i] * in[i];
    }
}

#+end_src


#+begin_src

-- hs

square :: [Double] -> [Double]
square []     = []
square (x:xs) = x*x : square xs

#+end_src

Example 3.

#+begin_src

// C
#include <stdio.h>

char *upercase(const char *in) {
    char *out = strdup(in);

    if (out != NULL) {
        for (size_t i = 0; out[i] != '\0'; i++) {
            out[i] = toupper(out[i]);
        }
    }
    return out;
}

#+end_src


#+begin_src

-- hs
import Data.Char (toUpper)

upperCase :: String -> String
upperCase []     = []
upperCase (x:xs) = toUpper x : upperCase xs

#+end_src

** Loops. Mapping

#+begin_src

squareXs :: Num a => [a] -> [a]
squareXs xs = map square xs
  where squareX :: Num a => a -> a
        squareX x = x * x

-- or
squareXs :: Num a => [a] -> [a]
squareXs xs = map squareX xs
  where squareX x = x * x

#+end_src

#+begin_src

import Data.Char (toUpper)

upperCase :: String -> String
upperCase xs = map toUpper xs

#+end_src

'map' signature

#+begin_src

:t map
-- map :: (a -> b) -> [a] -> [b]

#+end_src

Own implementation for practice.

#+begin_src

myMap :: (a -> b) -> [a] -> [b]
myMap _ []      = []
myMap fn (x:xs) = fn x : myMap fn xs

#+end_src

** Loops. Selection

to be done with 'filter'.

#+begin_src

:t filter
-- filter :: (a -> Bool) -> [a] -> [a]

#+end_src

Example:

#+begin_src

myFilter :: (a -> Bool) -> [a] -> [a]
myFilter _ [] = []
myFilter pred (x:xs)
  | pred x = x : myFilter pred xs
  | otherwise = myFilter pred xs

myFilter odd [1..10]
-- [1,3,5,7,9]

#+end_src

** Loops. Summaries

To be done with 'foldl' and 'foldr'.

Example of 'foldl':

#+begin_src

:t foldl
-- foldl :: (b -> a -> b) -> b -> [a] -> b

#+end_src

#+begin_src

myFoldl :: (b -> a -> b) -> b -> [a] -> b
myFoldl _ acc []      = acc
myFoldl fn acc (x:xs) = myFoldl fn (fn acc x) xs

myFoldl (+) 0 [1..10]
-- 55

myFoldl (*) 1 [1..5]
-- 120

myFoldl (\a x -> x*2 : a) [] [1..2]
-- [4,2]

-- myFoldl (/) 100 [5,2]
10.0
-- since 100 / 5 / 2 is 10

#+end_src

Example of 'foldr':

#+begin_src

:t foldr
foldr :: (a -> b -> b) -> b -> [a] -> b

#+end_src

#+begin_src

myFoldr :: (a -> b -> b) -> b -> [a] -> b
myFoldr _ acc []      = acc
myFoldr fn acc (x:xs) = (fn x (myFoldr fn acc xs))

myFoldr (+) 0 [1..10]
-- 55

myFoldr (*) 1 [1..5]
-- 120

myFoldr (\x a -> x*2 : a) [] [1..2]
-- [2,4]

myFoldr (/) 100 [5, 2]
-- 250.0
-- since 5 / (2 / 100) is 250

#+end_src

'foldr' replaces the empty list ('()') with the initial accumulator and every
constructor (':'') in the list with an application of the step function.

So

#+begin_src

foldr (/) 100 [5, 2]
-- is: foldr (/) 100 (5:2:())
-- which becomes: 5 / 2 / 100
-- and is evaluated from right: (5 / (2 / 100))

#+end_src


'Data.List' contains a `foldl'` function that acts like `foldl` but it is not
lazy and doesn't produce thunks (deferred computation).

#+begin_src

-- DANGER, DO NOT RUN THIS CODE
foldl (+) 0 [1..1000000000]
-- freezes, and/or throws error because of stack overflow

-- WARNING, it will likely freeze your computer for a while
foldl' (+) 0 [1..1000000000]
-- takes some time, but should return the result
-- 500000000500000000

#+end_src

** Further Reading

G. Hutton, A tutorial on the universality and expressiveness of fold.
to be found online at: https://people.cs.nott.ac.uk/pszgmh/fold.pdf

** Anonymous Functions

Anonymous (sometimes called lambda) functions are used in the form
'(\arg -> do_sth_with_arg)' or '(\arg1 arg2 -> do_sth_with_arg1_and_arg2)'.

** Partial Function Application

Partial function application is named *currying*.

Full function:

#+begin_src

:t dropWhile
-- dropWhile :: (a -> Bool) -> [a] -> [a]

#+end_src

Partially applied function:

#+begin_src

:m +Data.Char
:t dropWhile isSpace
-- dropWhile isSpace :: [Char] -> [Char]

#+end_src

Usage of partially applied functions (easy to create 'lstrip' from some other
programming languages):

#+begin_src

map (dropWhile isSpace) [" a", "f", "     e"]
-- ["a","f","e"]

#+end_src

In general, partial function application lets us avoid writing tiresome
throwaway functions.  In that respect, it's often more useful than anonymous
functions.

Another example of currying in use:

#+begin_src

niceSum :: [Integer] -> Integer
niceSum xs = foldl (+) 0 xs

-- or

niceSum :: [Integer] -> Integer
niceSum = foldl (+) 0
-- since foldr misses a list

#+end_src

** Sections

*Section* is when you enclose an operator in parentheses and supply its left or
right argument inside of them to get a partially applied function, e.g.

#+begin_src

map (2^) [1,2,3]
-- [2,4,8]

map (^2) [1,2,3]
-- [1,4,9]

#+end_src

** As-patterns

As patterns allow you to have a cookie and eat a cookie, e.g.

#+begin_src

suffixes :: [a] -> [[a]]
suffixes [] = []
suffixes xs@(_:xs') = xs : suffixes xs'

-- vs.

suffixes :: [a] -> [[a]]
suffixes [] = []
suffixes (x:xs) = (x:xs) : suffixes xs

#+end_src

Here, the as-pattern `@xs(_:xs')`` means "bind the variable 'xs' to the value that
matches the right side of the '@' symbol. As-patterns allow us to share data
instead of copying it (with '(x:xs)' match).
