#+title: Ch05
#+STARTUP: overview
#+STARTUP: indent
#+OPTIONS: \n: t

* JSON library
** JSON - Basic Info

see also: https://en.wikipedia.org/wiki/JSON

JSON stands for JavaScript Object Notation. It is often used for config files
and for sending structured data over a network.

A JSON object resembles a Python's dictionary. A JSON object contains key-value
pairs. A key is always a string. A value is either:

- string,
- number,
- boolean,
- null,
- array,
- object (so JSON is a recursive type)

We may express it in our program as:

#+begin_src

data JValue = JString String
            | JNumber Double
            | JBool Bool
            | JNull
            | JObject [(String, JValue)]
            | JArray [JValue]
            deriving (Eq, Ord, Show)

#+end_src

** Functions (mostly getters)

#+begin_src

getString :: JValue -> Maybe String
getString (JString s) = Just s
getString _           = Nothing

getInt :: JValue -> Maybe Int
getInt (JNumber n) = Just (truncate n)
getInt _           = Nothing

getDouble :: JValue -> Maybe Double
getDouble (JNumber n) = Just n
getDouble _           = Nothing

getBool :: JValue -> Maybe Bool
getBool (JBool b) = Just b
getBool _         = Nothing

getObject :: JValue -> Maybe [(String, JValue)]
getObject (JObject o) = Just o
getObject _           = Nothing

getArray :: JValue -> Maybe [JValue]
getArray (JArray a) = Just a
getArray _          = Nothing

isNull :: JValue -> Bool
isNull v = v == JNull

#+end_src

** The anatomy of a module

A source file begins with a module declaration, like:

#+begin_src

-- file: ch05/SimpleJSON.hs
module SimpleJSON
  (
    JValue(..)
  , getString
  , getInt
  , getDouble
  , getBool
  , getObject
  , getArray
  , isNull
  ) where

#+end_src

A file can only contain 1 module. The module name starts with a capital letter
and matches the name of its source file (exception Main module). Parentheses
contain a list of exports, the liens following `where` are a module's
body/definitions. `JValue(..)` means we export the type and all of its
constructors.

using

#+begin_src

-- file: ch05/SimpleJSON.hs
module SimpleJSON where

#+end_src

exports everything, whereas

#+begin_src

-- file: ch05/SimpleJSON.hs
module SimpleJSON () where

#+end_src

exports nothing (empty export list).

** Compilation

#+begin_src

ghc -c SimpleJSON.hs

#+end_src

`-c` is a linking option, that tells the compiler to only generate an object
code (`SimpleJSON.o` - object file, `SimpleJSON.hi` - interface file). Without
`-c` the compiler would attempt to generate a complete executable, which
requires `main` function.

** Program with Imports

The entry point of a program is `main` function inside `Main.hs` file:

#+begin_src

-- file ch05/Main.hs
module Main (main) where

import           SimpleJSON

main :: IO ()
main = print (JObject [("foo", JNumber 1), ("bar", JBool False)])

#+end_src

Module imports must appear at the beginning of a module, right after the module
declaration, but before other code.

Now we build program with:

#+begin_src

ghc -o simple Main.hs SimpleJSON.hs

#+end_src

The program will try to create executable. The `-o` is the name of the
executable to be created (on Windows it will be with `.exe` suffix).

We must explicitly list every file that contains the code thet should end in the
executable. For compilation one can pass a mixture of source and object (like
`SimpleJSON.o`) files.

** Printing JSON

Attempt 1 (simple and direct approach):

#+begin_src

-- file ch05/PutJSON.hs
module PutJSON where

import           Data.List  (intercalate)
import           SimpleJSON

renderJValue :: JValue -> String
renderJValue (JString s)   = show s
renderJValue (JNumber n)   = show n
renderJValue (JBool True)  = "true"
renderJValue (JBool False) = "false"
renderJValue JNull         = "null"
renderJValue (JObject o)         = "{" ++ pairs o ++ "}"
  where paris [] = ""
        pairs ps = intercalate ", " (map renderPair ps)
        renderPair (k, v) = show k ++ ": " ++ renderJValue v
renderJValue (JArray a)         = "[" ++ values a ++ "]"
  where values [] = ""
        values vs = intercalate ", " (map renderJValue vs)


#+end_src

Separation of pure (`renderJValue`) code from impure (`putJValue`).

#+begin_src

-- file ch05/PutJSON.hs continued

putJValue :: JValue -> IO ()
putJValue v = putStrLn (renderJValue v)

#+end_src

** Type Inference - double edge sword

Despite a powerful type inference system one should add types to avoid errors,
further own understanding of the code, ease oneself with code maintenance, avoid
disagreements with the compiler, e.g.

#+begin_src

upcaseFirst (c:cs) = toUpper c -- forgot ":cs" here

#+end_src

Here the programmer wanted type: `String -> String`, but got `String -> Char`
(the correct type inferred by the compiler based on the function definition) and
since they didn't add types they remain unaware of it. The mismatch will occur
somewhere else and will be more difficult to pinpoint and debug.
